# os: linux and sudo: false is assumed, which means it is using container-based Ubuntu 12.04
language: python
cache:
  - pip
# build matrix: different python and pandoc versions
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  # - "3.5-dev" # 3.5 development branch
  # - "3.6-dev" # 3.6 development branch
  # - "nightly" # currently points to 3.7-dev
  # pypy (version info from [Changelogs â€” PyPy documentation](http://doc.pypy.org/en/latest/index-of-whatsnew.html))
  - "pypy"  # PyPy2.7 5.3.1 (CPython 2.7 compatible)
  - "pypy3" # PyPy3 2.4.0 (CPython 3.2 compatible)
env:
  # - pandocVersion=1.13.2
  # - pandocVersion=1.14
  # - pandocVersion=1.14.0.1
  # - pandocVersion=1.14.1
  # - pandocVersion=1.15
  # - pandocVersion=1.15.0.5
  # - pandocVersion=1.15.0.6
  # - pandocVersion=1.15.1
  # - pandocVersion=1.15.2
  # - pandocVersion=1.16
  # - pandocVersion=1.16.0.1
  # - pandocVersion=1.16.0.2
  # - pandocVersion=1.17
  # - pandocVersion=1.17.0.1
  # - pandocVersion=1.17.0.2
  # - pandocVersion=1.17.1
  - pandocVersion=1.17.2
  # - pandocVersion=1.18
  - pandocVersion=latest
matrix:
  allow_failures:
    - python: "3.5-dev"
    - python: "3.6-dev"
    - python: "nightly"
    - python: "pypy3"
    # - env: pandocVersion=1.13.2
    # - env: pandocVersion=1.14
    # - env: pandocVersion=1.14.0.1
    # - env: pandocVersion=1.14.1
    # - env: pandocVersion=1.15
    # - env: pandocVersion=1.15.0.5
    # - env: pandocVersion=1.15.0.6
    # - env: pandocVersion=1.15.1
    # - env: pandocVersion=1.15.2
  fast_finish: true
before_install:
  - |
    if [[ $pandocVersion == "latest" ]]; then
      url="https://github.com/jgm/pandoc/releases/latest"
    else
      url="https://github.com/jgm/pandoc/releases/tag/$pandocVersion"
    fi
    path=$(curl -L $url | grep -o '/jgm/pandoc/releases/download/.*-amd64.deb')
    downloadUrl="https://github.com$path"
    file=${path##*/}
install:
  - wget $downloadUrl &&
    sudo dpkg -i $file
  - pip install -U pip
  - pip install -U future # temporary fix on panflute 1.8.1
  - pip install -e .[test]
# command to run tests
script:
  - make -j4 test
after_success:
  - if [[ "$pandocVersion" == "latest" ]] && [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then coveralls; else printf "skip coveralls"; fi;
deploy:
  provider: pypi
  user: ickc
  password: $pypi_password
  skip_cleanup: true
  on:
    tags: true
    python: "3.5"
    condition: $pandocVersion = latest
