# os: linux and sudo: false is assumed, which means it is using container-based Ubuntu 14.04
language: python
cache: pip
# build matrix: different python and pandoc versions
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  # pypy (version info from [Changelogs â€” PyPy documentation](http://doc.pypy.org/en/latest/index-of-whatsnew.html))
  - "pypy"
  - "pypy3.5"
env:
  - pandocVersion=1.19.2.1
  - pandocVersion=2.2.3.2
  - pandocVersion=latest
# matrix:
#   allow_failures:
#     - python: "3.4"
#     - env: pandocVersion=1.19.2.1
#   fast_finish: true
# install dependencies
install:
  - pip install -U pip
  # latest pip dropped support for py3.2, which is the version of python in pypy3
  # - if [[ "$TRAVIS_PYTHON_VERSION" != "pypy3" ]]; then pip install -U pip; fi
  # setup.py requires a minimum version of setuptools.  The virtual environments
  # of some of the python versions does not have a sufficiently new setuptools
  # version.
  - |
    SETUPTOOLS_VERSION=$(easy_install --version | cut -d' ' -f2) &&
    dpkg --compare-versions ${SETUPTOOLS_VERSION} lt 20.6.8 && pip install -U setuptools ||
    echo "Setuptools ${SETUPTOOLS_VERSION} is suficiently new (>=20.6.8)"
  - pip install -e .[test]
  # pandoc
  - |
    downloadUrl=$(python -c 'import requests, sys; v = sys.argv[1]; url = "https://api.github.com/repos/jgm/pandoc/releases/" + (v if v == "latest" else ("tags/" + v)); print(next(i["browser_download_url"] for i in requests.get(url).json()["assets"] if i["name"][-3:] == "deb"))' $pandocVersion) &&
    wget $downloadUrl &&
    sudo dpkg -i ${downloadUrl##*/}
before_script:
  # pasteurize for py2 only, except setup.py & pantable/version.py
  - |
    [[ "$TRAVIS_PYTHON_VERSION" == "2.7" || "$TRAVIS_PYTHON_VERSION" == "pypy" ]] && find \! \( -path './setup.py' -o -path './pantable/version.py' \) -exec pasteurize -wnj 4 {} +
# command to run tests
script:
  - make -j3 test
after_success:
  - |
    [[ "$pandocVersion" == "latest" && "$TRAVIS_PYTHON_VERSION" == "3.6" ]] && coveralls
before_deploy:
  # build unpasteurized python3 wheel
  - python3 setup.py bdist_wheel
  # pasteurize except setup.py & pantable/version.py
  - find \! \( -path './setup.py' -o -path './pantable/version.py' \) -exec pasteurize -wnj 4 {} +
  # prepare wheel for py2
  - pip2 install wheel
  - python2 setup.py bdist_wheel
deploy:
  provider: pypi
  user: ickc
  password: $pypi_password
  # do not add bdist_wheel here, since it is done above
  distributions: "sdist"
  skip_cleanup: true
  on:
    tags: true
    python: "3.6"
    condition: $pandocVersion = latest
